// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwbhppmlxubyukkzsqkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3YmhwcG1seHVieXVra3pzcWtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzcxODgsImV4cCI6MjA2Mzg1MzE4OH0.2RDV-zlOCnG4eXhrHVj7mQk81ogKhtcYPFCL25u2YDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);